src/Entity/Ev.php
<?php

namespace App\Entity;

use App\Repository\EvRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvRepository::class)
 */
class Ev
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Nom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $lieu;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(?string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Controller/Zone1Controller.php
<?php

namespace App\Controller;

use App\Entity\ZoneDeLoisir;
use App\Entity\Reservation;

use App\Form\ReservationType;


use App\Form\FormmType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\RestaurationRepository;

use Symfony\Component\HttpFoundation\File\UploadedFile;

use App\Entity\Hotel;
use App\Form\Hotel1Type;


/**
 * @Route("/zone1")
 */
class Zone1Controller extends AbstractController
{
    /**
     * @Route("/", name="zone1_index", methods={"GET"})
     */
    public function index(): Response
    {
        $zoneDeLoisirs = $this->getDoctrine()
            ->getRepository(ZoneDeLoisir::class)
            ->findAll();

        return $this->render('zone1/index.html.twig', [
            'zone_de_loisirs' => $zoneDeLoisirs,
        ]);
    }
  /**
     * @Route("/h", name="hotel_index", methods={"GET"})
     */
    public function index2(): Response
    {
        $hotels = $this->getDoctrine()
            ->getRepository(Hotel::class)
            ->findAll();

        return $this->render('hotel/index.html.twig', [
            'hotels' => $hotels,
        ]);
    }
    /**
     * @Route("/new", name="zone1_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
       
       
       
        $zoneDeLoisir = new ZoneDeLoisir();
        $form = $this->createForm(FormmType::class, $zoneDeLoisir);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['image']->getData();

            $file->move("images/", $file->getClientOriginalName());
            $zoneDeLoisir->setImage("images/".$file->getClientOriginalName());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($zoneDeLoisir);
            $entityManager->flush();
            return $this->redirectToRoute('zone1_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('zone1/new.html.twig', [
            'zone_de_loisir' => $zoneDeLoisir,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="zone1_show", methods={"GET"})
     */
    public function show(ZoneDeLoisir $zoneDeLoisir): Response
    {
        return $this->render('zone1/show.html.twig', [
            'zone_de_loisir' => $zoneDeLoisir,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="zone1_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, ZoneDeLoisir $zoneDeLoisir): Response
    {
        $form = $this->createForm(FormmType::class, $zoneDeLoisir);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('zone1_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('zone1/edit.html.twig', [
            'zone_de_loisir' => $zoneDeLoisir,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="zone1_delete", methods={"POST"})
     */
    public function delete(Request $request, ZoneDeLoisir $zoneDeLoisir): Response
    {
        if ($this->isCsrfTokenValid('delete'.$zoneDeLoisir->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($zoneDeLoisir);
            $entityManager->flush();
        }

        return $this->redirectToRoute('zone1_index', [], Response::HTTP_SEE_OTHER);
    }
     /**
     * @Route("/new1/{id}", name="reservation_new1", methods={"GET","POST"})
     */
    public function new1(Request $request ): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);
     
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

      /**
     * @Route("/", name="zone1_index2", methods={"GET"})
     */
    public function index1(): Response
    {
        $zoneDeLoisirs = $this->getDoctrine()
            ->getRepository(ZoneDeLoisir::class)
            ->findAll();

        return $this->render('zone1/index.html.twig', [
            'zone_de_loisirs' => $zoneDeLoisirs,
        ]);
    }
    
}

templates/zone1/_delete_form.html.twig
<form method="post" action="{{ path('zone1_delete', {'id': zone_de_loisir.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ zone_de_loisir.id) }}">
    <button class="btn">Delete</button>
</form>

templates/zone1/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/zone1/edit.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Edit ZoneDeLoisir{% endblock %}

{% block body %}
    <h1>Edit ZoneDeLoisir</h1>

    {{ include('zone1/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('zone1_index') }}">back to list</a>

    {{ include('zone1/_delete_form.html.twig') }}
{% endblock %}

templates/zone1/index.html.twig
{% extends 'base1.html.twig' %}

{% block title %}ZoneDeLoisir index{% endblock %}

{% block body %}
    <h1>ZoneDeLoisir index</h1>

<section class="food_section layout_padding-bottom">
    <div class="container">
        <div class="heading_container heading_center">
            <h2>
                Our Guide
            </h2>
        </div>
    
          
        <ul class="filters_menu">
            <li class="active" data-filter="*">Restaurations</li>
            <a href="{{ path('hotel_index') }}"><li data-filter=".burger" class="">Hotels</li></a>
            <li data-filter=".pizza" class="">Zones Touristiques</li>
            <li data-filter=".pasta" class="">zones Archéologiques</li>
        </ul>

        <div class="filters-content">

            <div class="row grid">

                    {% for zone_de_loisir in zone_de_loisirs %}
                <div class="col-sm-6 col-lg-4 all piza ">
                    <div class="box">
                        <div>
                            <div class="img-box">
                                <img src="{{ asset(zone_de_loisir.image) }} " alt="">
                            </div>
                            <div class="detail-box">
                                <h5>
                                 Nom :  {{ zone_de_loisir.nom }}
                                </h5>

                                <p> telephone : {{ zone_de_loisir.tel }} </p>

                                <p> Email :   {{ zone_de_loisir.email }}</p>

                                <p> Page Web :  {{ zone_de_loisir.prix }}   </p>

                                <p> Adresse : {{ zone_de_loisir.nbplace }}</p>
                                 <p> Adresse : {{ zone_de_loisir.nbmax }}</p>

                                    <div class="options">
                                       <a href="{{ path('zone1_show', {'id': zone_de_loisir.id}) }}">show</a>
 <a href="{{ path('reservation_new1', {'id': zone_de_loisir.id}) }}">reserver </a>

                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
                    {% endfor %}


            </div>

        <div class="btn-box">
            <a href="">
                View More
            </a>
        </div>
    </div>
    </div>
</section>

{% endblock %}

templates/zone1/new.html.twig
{% extends 'base1.html.twig' %}

{% block title %}New ZoneDeLoisir{% endblock %}

{% block body %}
    <h1>Create new ZoneDeLoisir</h1>

    {{ include('zone1/_form.html.twig') }}

    <a href="{{ path('zone1_index') }}">back to list</a>
{% endblock %}

templates/zone1/show.html.twig
{% extends 'base1.html.twig' %}

{% block title %}ZoneDeLoisir{% endblock %}

{% block body %}
    <h1>ZoneDeLoisir</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ zone_de_loisir.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ zone_de_loisir.nom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ zone_de_loisir.adresse }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ zone_de_loisir.tel }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ zone_de_loisir.prix }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ zone_de_loisir.type }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ zone_de_loisir.email }}</td>
            </tr>
            <tr>
                <th>Nbplace</th>
                <td>{{ zone_de_loisir.nbplace }}</td>
            </tr>
            <tr>
                <th>Nbmax</th>
                <td>{{ zone_de_loisir.nbmax }}</td>
            </tr>
            <tr>
                <th>Nbmax</th>
                             <img src="{{ asset(zone_de_loisir.image) }} " alt="">

            </tr>
        </tbody>
    </table>

    <a href="{{ path('zone1_index') }}">back to list</a>

    <a href="{{ path('zone1_edit', {'id': zone_de_loisir.id}) }}">edit</a>

{% endblock %}